name: newsnow monitor

on:
  schedule:
    # 한국 시간 기준: 09:00, 13:30, 17:00, 19:30 ㅡ,.ㅡ
    - cron: '0 0 * * *'    # 09:00 KST
    - cron: '30 4 * * *'   # 13:30 KST
    - cron: '0 8 * * *'    # 17:00 KST
    - cron: '30 10 * * *'  # 19:30 KST
  workflow_dispatch:       # 필요할 때 수동으로 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install cloudscraper requests

      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python newsnow_monitor.py

      - name: Commit DB changes
        run: |
          git config --global user.name "kini-bot"
          git config --global user.email "bot@github.com"
          git add sent_urls.txt
          git commit -m "Update sent URLs DB (Time-filtered)" || exit 0
          git push
